spring.application.name=PetStore
spring.datasource.url=jdbc:postgresql://localhost:5432/Pet Store
spring.datasource.username=postgres
spring.datasource.password=razmovski123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
